[theme]
base = "light"
primaryColor = "#E30613"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F4F5"
textColor = "#18181B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
